"""initial

Revision ID: 0e9497533b08
Revises: 
Create Date: 2026-07-19 17:59:20.902853

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9497533b08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_applications',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('resume_path', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_applications_created_status', 'career_applications', ['created_at', 'status'], unique=False)
    op.create_index('idx_applications_position_status', 'career_applications', ['position', 'status'], unique=False)
    op.create_index(op.f('ix_career_applications_email'), 'career_applications', ['email'], unique=False)
    op.create_index(op.f('ix_career_applications_name'), 'career_applications', ['name'], unique=False)
    op.create_index(op.f('ix_career_applications_position'), 'career_applications', ['position'], unique=False)
    op.create_index(op.f('ix_career_applications_status'), 'career_applications', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contacts_email_status', 'contacts', ['email', 'status'], unique=False)
    op.create_index('idx_contacts_status_created', 'contacts', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_status'), 'contacts', ['status'], unique=False)
    op.create_table('feedbacks',
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedbacks_category_rating', 'feedbacks', ['category', 'rating'], unique=False)
    op.create_index('idx_feedbacks_created', 'feedbacks', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedbacks_category'), 'feedbacks', ['category'], unique=False)
    op.create_table('newsletters',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_newsletters_status', 'newsletters', ['status'], unique=False)
    op.create_index('idx_newsletters_subscribed', 'newsletters', ['is_subscribed', 'subscribed_at'], unique=False)
    op.create_index(op.f('ix_newsletters_email'), 'newsletters', ['email'], unique=True)
    op.create_table('quote_requests',
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('budget_range', sa.String(length=20), nullable=True),
    sa.Column('timeline', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotes_created_status', 'quote_requests', ['created_at', 'status'], unique=False)
    op.create_index('idx_quotes_service_status', 'quote_requests', ['service', 'status'], unique=False)
    op.create_index(op.f('ix_quote_requests_email'), 'quote_requests', ['email'], unique=False)
    op.create_index(op.f('ix_quote_requests_name'), 'quote_requests', ['name'], unique=False)
    op.create_index(op.f('ix_quote_requests_service'), 'quote_requests', ['service'], unique=False)
    op.create_index(op.f('ix_quote_requests_status'), 'quote_requests', ['status'], unique=False)
    op.create_table('resources',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_resources_slug'),
    sa.UniqueConstraint('title', name='uq_resources_title')
    )
    op.create_index('idx_resources_category_status', 'resources', ['category', 'status'], unique=False)
    op.create_index('idx_resources_published', 'resources', ['published_date'], unique=False)
    op.create_index('idx_resources_status_created', 'resources', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_table('services',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_services_slug'),
    sa.UniqueConstraint('title', name='uq_services_title')
    )
    op.create_index('idx_services_featured_order', 'services', ['is_featured', 'display_order'], unique=False)
    op.create_index('idx_services_order', 'services', ['display_order'], unique=False)
    op.create_index(op.f('ix_services_status'), 'services', ['status'], unique=False)
    op.create_table('solutions',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_solutions_slug'),
    sa.UniqueConstraint('title', name='uq_solutions_title')
    )
    op.create_index('idx_solutions_category_order', 'solutions', ['category', 'display_order'], unique=False)
    op.create_index('idx_solutions_featured_order', 'solutions', ['is_featured', 'display_order'], unique=False)
    op.create_index(op.f('ix_solutions_category'), 'solutions', ['category'], unique=False)
    op.create_index(op.f('ix_solutions_status'), 'solutions', ['status'], unique=False)
    op.create_table('technologies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_technologies_name'),
    sa.UniqueConstraint('slug', name='uq_technologies_slug')
    )
    op.create_index('idx_technologies_category_order', 'technologies', ['category', 'display_order'], unique=False)
    op.create_index('idx_technologies_featured_order', 'technologies', ['is_featured', 'display_order'], unique=False)
    op.create_index(op.f('ix_technologies_category'), 'technologies', ['category'], unique=False)
    op.create_index(op.f('ix_technologies_status'), 'technologies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technologies_status'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_category'), table_name='technologies')
    op.drop_index('idx_technologies_featured_order', table_name='technologies')
    op.drop_index('idx_technologies_category_order', table_name='technologies')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_solutions_status'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_category'), table_name='solutions')
    op.drop_index('idx_solutions_featured_order', table_name='solutions')
    op.drop_index('idx_solutions_category_order', table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_services_status'), table_name='services')
    op.drop_index('idx_services_order', table_name='services')
    op.drop_index('idx_services_featured_order', table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_index('idx_resources_status_created', table_name='resources')
    op.drop_index('idx_resources_published', table_name='resources')
    op.drop_index('idx_resources_category_status', table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_quote_requests_status'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_service'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_name'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_email'), table_name='quote_requests')
    op.drop_index('idx_quotes_service_status', table_name='quote_requests')
    op.drop_index('idx_quotes_created_status', table_name='quote_requests')
    op.drop_table('quote_requests')
    op.drop_index(op.f('ix_newsletters_email'), table_name='newsletters')
    op.drop_index('idx_newsletters_subscribed', table_name='newsletters')
    op.drop_index('idx_newsletters_status', table_name='newsletters')
    op.drop_table('newsletters')
    op.drop_index(op.f('ix_feedbacks_category'), table_name='feedbacks')
    op.drop_index('idx_feedbacks_created', table_name='feedbacks')
    op.drop_index('idx_feedbacks_category_rating', table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_contacts_status'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index('idx_contacts_status_created', table_name='contacts')
    op.drop_index('idx_contacts_email_status', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_career_applications_status'), table_name='career_applications')
    op.drop_index(op.f('ix_career_applications_position'), table_name='career_applications')
    op.drop_index(op.f('ix_career_applications_name'), table_name='career_applications')
    op.drop_index(op.f('ix_career_applications_email'), table_name='career_applications')
    op.drop_index('idx_applications_position_status', table_name='career_applications')
    op.drop_index('idx_applications_created_status', table_name='career_applications')
    op.drop_table('career_applications')
    # ### end Alembic commands ###
