name: ci basic pipleline
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

    
env:
    APP_NAME: "VALP_SYSTEMS"
    PYTHON_VERSION: "3.14"



jobs:
    hello_world:
        runs-on: ubuntu-latest

        steps:
            - name: code_checkout
              uses: actions/checkout@v4

            - name: calling the environment variables
              run: |
                echo "Application Name: ${{env.APP_NAME}}"
                echo "Application Version: ${{env.PYTHON_VERSION}}"
                echo "Runner Os version: ${{runner.os}}"
                echo "Runner Arch: ${{runner.arch}}"
                echo "Github ref: ${{github.ref}}"
                echo "Triggered by: ${{github.event_name}}"

            - name: output values define
              id: my-output
              run: |
                echo "build_number=$GITHUB_RUN_NUMBER" >> "$GITHUB_OUTPUT"
                echo "time_stamp=$(date -u +%Y-%m-%dT%H:%m:%SZ)" >> "$GITHUB_OUTPUT"

            - name: calling_output Values
              run: |
                echo "Build_Number: ${{steps.my-output.outputs.build_number}}"
                echo "Time_stamp: ${{steps.my-output.outputs.time_stamp}}"

    conditional-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: condition specific check if it is main brach only
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: echo "this will run on the only push and main branch"

            - name: this will run on only the pull_request
              if: github.event_name == 'pull_request'
              run: echo "this will run only the pull request"

    matrix_check:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.11", "3.12", "3.14"]

            fail-fast: false

        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: setup python ${{matrix.python-version}}
              uses: actions/setup-python@v5
              with:
                python-version: ${{matrix.python-version}}

            - name: check the version of python
              run: python --version 
        


